// <auto-generated />
using System;
using FYP1_System___Individual.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FYP1_System___Individual.Migrations
{
    [DbContext(typeof(FYP1_System_Context))]
    [Migration("20250522140657_add_online_form")]
    partial class add_online_form
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FYP1_System___Individual.Models.AcademicProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcademicPrograms");
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EvaluationStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Evaluator1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Evaluator2Id")
                        .HasColumnType("int");

                    b.Property<string>("EvaluatorComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OnlineProposalFormPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<string>("ProposalDocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Session")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorStatus")
                        .HasColumnType("int");

                    b.Property<int?>("TentativeSupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Evaluator1Id");

                    b.HasIndex("Evaluator2Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TentativeSupervisorId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Lecturer", b =>
                {
                    b.HasBaseType("FYP1_System___Individual.Models.User");

                    b.Property<int?>("Domain")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.HasIndex("ProgramId");

                    b.ToTable("Lecturers", (string)null);
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Student", b =>
                {
                    b.HasBaseType("FYP1_System___Individual.Models.User");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.HasIndex("ProgramId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Proposal", b =>
                {
                    b.HasOne("FYP1_System___Individual.Models.Lecturer", "Evaluator1")
                        .WithMany("EvaluatedAsFirst")
                        .HasForeignKey("Evaluator1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP1_System___Individual.Models.Lecturer", "Evaluator2")
                        .WithMany("EvaluatedAsSecond")
                        .HasForeignKey("Evaluator2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP1_System___Individual.Models.Student", "Student")
                        .WithMany("Proposals")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP1_System___Individual.Models.Lecturer", "Supervisor")
                        .WithMany("SupervisedProposals")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP1_System___Individual.Models.Lecturer", "TentativeSupervisor")
                        .WithMany("TentativeSupervisedProposals")
                        .HasForeignKey("TentativeSupervisorId");

                    b.Navigation("Evaluator1");

                    b.Navigation("Evaluator2");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");

                    b.Navigation("TentativeSupervisor");
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Lecturer", b =>
                {
                    b.HasOne("FYP1_System___Individual.Models.User", null)
                        .WithOne()
                        .HasForeignKey("FYP1_System___Individual.Models.Lecturer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP1_System___Individual.Models.AcademicProgram", "Program")
                        .WithMany("Lecturers")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Student", b =>
                {
                    b.HasOne("FYP1_System___Individual.Models.User", null)
                        .WithOne()
                        .HasForeignKey("FYP1_System___Individual.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP1_System___Individual.Models.AcademicProgram", "Program")
                        .WithMany("Students")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.AcademicProgram", b =>
                {
                    b.Navigation("Lecturers");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Lecturer", b =>
                {
                    b.Navigation("EvaluatedAsFirst");

                    b.Navigation("EvaluatedAsSecond");

                    b.Navigation("SupervisedProposals");

                    b.Navigation("TentativeSupervisedProposals");
                });

            modelBuilder.Entity("FYP1_System___Individual.Models.Student", b =>
                {
                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
